
name: Linux builder containers

on:
  workflow_dispatch:

#  schedule:
#  - cron: '30 4 * * 1'

# =========================================================================

jobs:

  # -----------------------------------------------------------------------
  x86_64:
    runs-on: ubuntu-18.04
    name: Build pak builder containers, x86_64
    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: '4.3' }
          - { r: '4.2' }
          - { r: '4.1' }
          - { r: '4.0' }
          - { r: '3.6' }
          - { r: '3.5' }
          - { r: '3.4' }

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
          docker build --pull \
              --build-arg R_MAJOR=${{ matrix.config.r }} \
              -t ghcr.io/r-lib/pak-builder:x86_64-${{ matrix.config.r }} \
              -f tools/build/linux/Dockerfile-builder .

    - name: Push
      run: |
          docker push ghcr.io/r-lib/pak-builder:x86_64-${{ matrix.config.r }}

  # -----------------------------------------------------------------------
  aarch64:
    runs-on: [linux-arm64]
    name: Build pak builder containers, aarch64
    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: '4.3' }
          - { r: '4.2' }
          - { r: '4.1' }
          - { r: '4.0' }
          - { r: '3.6' }
          - { r: '3.5' }
          - { r: '3.4' }

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
          docker build --pull \
              --build-arg R_MAJOR=${{ matrix.config.r }} \
              -t ghcr.io/r-lib/pak-builder:aarch64-${{ matrix.config.r }} \
              -f tools/build/linux/Dockerfile-builder .

    - name: Push
      run: |
          docker push ghcr.io/r-lib/pak-builder:aarch64-${{ matrix.config.r }}
